import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedZakisetyawan2gmailcomWidget4.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedZakieass_Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedKotaMalangIndonesiaWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedImage25Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedProfilandaWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedEllipse5Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedRectangle140Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedImage27Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedRectangle144Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedImage12Widget18.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedImage26Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedBuangperubahanWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedRectangle141Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedRectangle139Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedSimpanperubahanWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedRectangle143Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget1/generated/GeneratedRectangle138Widget3.dart';

/* Frame CRU profil & Log-out
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCRUprofilLogoutWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedRectangle138Widget3(),
              ),
              Positioned(
                left: 158.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 25.0,
                child: GeneratedProfilandaWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage12Widget18(),
              ),
              Positioned(
                left: 142.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedEllipse5Widget5(),
              ),
              Positioned(
                left: 112.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 30.0,
                child: GeneratedRectangle139Widget3(),
              ),
              Positioned(
                left: 82.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedRectangle140Widget3(),
              ),
              Positioned(
                left: 82.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedRectangle141Widget3(),
              ),
              Positioned(
                left: 285.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage25Widget1(),
              ),
              Positioned(
                left: 305.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage26Widget1(),
              ),
              Positioned(
                left: 305.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage27Widget1(),
              ),
              Positioned(
                left: 147.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 25.0,
                child: GeneratedRectangle143Widget3(),
              ),
              Positioned(
                left: 147.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 25.0,
                child: GeneratedRectangle144Widget3(),
              ),
              Positioned(
                left: 156.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 17.0,
                child: GeneratedBuangperubahanWidget1(),
              ),
              Positioned(
                left: 152.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 17.0,
                child: GeneratedSimpanperubahanWidget1(),
              ),
              Positioned(
                left: 174.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 23.0,
                child: GeneratedZakieass_Widget4(),
              ),
              Positioned(
                left: 115.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 23.0,
                child: GeneratedZakisetyawan2gmailcomWidget4(),
              ),
              Positioned(
                left: 128.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 20.0,
                child: GeneratedKotaMalangIndonesiaWidget3(),
              )
            ]),
      ),
    ));
  }
}
