import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedsignupwidget1/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/makanterusapp/generatedsignupwidget1/generated/GeneratedSignupWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedsignupwidget1/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/makanterusapp/generatedsignupwidget1/generated/GeneratedGroup20Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedsignupwidget1/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/makanterusapp/generatedsignupwidget1/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/makanterusapp/generatedsignupwidget1/generated/GeneratedGroup16Widget1.dart';

/* Frame Sign-up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 290.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 700.0,
                height: 400.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 570.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 47.0,
                child: GeneratedSignupWidget2(),
              ),
              Positioned(
                left: 400.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 470.0,
                height: 30.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 400.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 470.0,
                height: 30.0,
                child: GeneratedGroup16Widget1(),
              ),
              Positioned(
                left: 400.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 470.0,
                height: 30.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 540.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 40.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 870.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 20.0,
                child: GeneratedGroup20Widget1(),
              )
            ]),
      ),
    ));
  }
}
