import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedGroup12Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle65Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle66Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle9Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedLine10Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedGroup13Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedLine7Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedLine11Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle6Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle7Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedLine6Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedLine8Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedLine5Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle62Widget22.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedKategoriWidget12.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedGroup11Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedLine12Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle8Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle63Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle61Widget27.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedLine9Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget1/generated/GeneratedRectangle64Widget15.dart';

/* Frame Tampilan awal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTampilanawalWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle6Widget5(),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine5Widget7(),
              ),
              Positioned(
                left: 16.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine6Widget6(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle7Widget5(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle8Widget5(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle9Widget5(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget12(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine7Widget5(),
              ),
              Positioned(
                left: 336.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine8Widget5(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine9Widget5(),
              ),
              Positioned(
                left: 656.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine10Widget5(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine11Widget5(),
              ),
              Positioned(
                left: 976.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine12Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedGroup11Widget5(),
              ),
              Positioned(
                left: 19.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 611.0,
                height: 324.0,
                child: GeneratedGroup12Widget5(),
              ),
              Positioned(
                left: 656.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 610.0,
                height: 324.0,
                child: GeneratedGroup13Widget5(),
              ),
              Positioned(
                left: 19.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle61Widget27(),
              ),
              Positioned(
                left: 336.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle62Widget22(),
              ),
              Positioned(
                left: 180.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle65Widget5(),
              ),
              Positioned(
                left: 816.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle66Widget5(),
              ),
              Positioned(
                left: 656.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle63Widget12(),
              ),
              Positioned(
                left: 976.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle64Widget15(),
              )
            ]),
      ),
    ));
  }
}
