import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget3/generated/GeneratedGroupWidget5.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget3/generated/GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak5.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget3/generated/GeneratedImage9Widget3.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget3/generated/Generated13KWidget4.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget3/generated/GeneratedImage7Widget4.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget3/generated/GeneratedRectangle91Widget5.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget3/generated/GeneratedGroup47Widget11.dart';

/* Frame Deskripsi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeskripsiWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroupWidget5(),
              ),
              Positioned(
                left: 28.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 224.0,
                child: GeneratedRectangle91Widget5(),
              ),
              Positioned(
                left: 34.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 182.0,
                child:
                    GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak5(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget11(),
              ),
              Positioned(
                left: 350.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage7Widget4(),
              ),
              Positioned(
                left: 352.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 25.0,
                child: Generated13KWidget4(),
              ),
              Positioned(
                left: 350.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage9Widget3(),
              )
            ]),
      ),
    ));
  }
}
