import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedLine6Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedGroup13Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedLine9Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedLine8Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle6Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle62Widget23.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle63Widget13.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedLine10Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle66Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle64Widget16.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedGroup11Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedKategoriWidget13.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedLine7Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedLine5Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedGroup12Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedLine11Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle65Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedLine12Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle61Widget28.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle9Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle7Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget2/generated/GeneratedRectangle8Widget6.dart';

/* Frame Tampilan awal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTampilanawalWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle6Widget6(),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine5Widget8(),
              ),
              Positioned(
                left: 16.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine6Widget7(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle7Widget6(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle8Widget6(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle9Widget6(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget13(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine7Widget6(),
              ),
              Positioned(
                left: 336.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine8Widget6(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine9Widget6(),
              ),
              Positioned(
                left: 656.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine10Widget6(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine11Widget6(),
              ),
              Positioned(
                left: 976.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine12Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedGroup11Widget6(),
              ),
              Positioned(
                left: 19.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 611.0,
                height: 324.0,
                child: GeneratedGroup12Widget6(),
              ),
              Positioned(
                left: 656.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 610.0,
                height: 324.0,
                child: GeneratedGroup13Widget6(),
              ),
              Positioned(
                left: 19.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle61Widget28(),
              ),
              Positioned(
                left: 336.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle62Widget23(),
              ),
              Positioned(
                left: 180.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle65Widget6(),
              ),
              Positioned(
                left: 816.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle66Widget6(),
              ),
              Positioned(
                left: 656.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle63Widget13(),
              ),
              Positioned(
                left: 976.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle64Widget16(),
              ),
              Positioned(
                left: 1056.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 36.0,
                child: GeneratedGroup19Widget(),
              )
            ]),
      ),
    ));
  }
}
