import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak6.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedImage29Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedRectangle100Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedImage4Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedRectangle123Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedGroup120Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedRectangle11Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedRectangle125Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedGroupWidget6.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedLine49Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedKomentarWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget1/generated/GeneratedLine50Widget3.dart';

/* Frame Komentar & Like
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKomentarLikeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 34.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 182.0,
                child:
                    GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak6(),
              ),
              Positioned(
                left: 0.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 347.0,
                child: GeneratedRectangle11Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroupWidget6(),
              ),
              Positioned(
                left: 28.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 423.4725341796875,
                height: 1.0,
                child: GeneratedLine49Widget3(),
              ),
              Positioned(
                left: 388.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 424.3229675292969,
                height: 1.0,
                child: GeneratedLine50Widget3(),
              ),
              Positioned(
                left: 27.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 224.0,
                child: GeneratedRectangle125Widget2(),
              ),
              Positioned(
                left: 343.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 3.0,
                height: 1.0,
                child: GeneratedRectangle100Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 40.0,
                child: GeneratedRectangle123Widget4(),
              ),
              Positioned(
                left: 10.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 25.0,
                child: GeneratedKomentarWidget3(),
              ),
              Positioned(
                left: 380.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage4Widget10(),
              ),
              Positioned(
                left: 350.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage29Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 70.0,
                child: GeneratedGroup120Widget3(),
              )
            ]),
      ),
    ));
  }
}
