import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget1/generated/GeneratedGroup48Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget1/generated/GeneratedZakiEkaASWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget1/generated/GeneratedZakieass_Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget1/generated/GeneratedZakisetyawan2gmailcomWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget1/generated/GeneratedGroup57Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget1/generated/Generated1Widget.dart';

/* Frame Manage user
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManageuserWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget7(),
              ),
              Positioned(
                left: 22.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 567.0,
                child: GeneratedGroup57Widget1(),
              ),
              Positioned(
                left: 267.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 14.0,
                child: GeneratedZakiEkaASWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 23.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 17.0,
                child: GeneratedZakieass_Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 17.0,
                child: GeneratedZakisetyawan2gmailcomWidget(),
              )
            ]),
      ),
    ));
  }
}
