import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup9Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedRectangle41Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedBackgroundWidget31.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup46Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup108Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup104Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup109Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup103Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedMakanTerusWidget4.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup6Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup105Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup88Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedImage1Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedBackgroundWidget30.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget1/generated/GeneratedGroup102Widget4.dart';

/* Frame Halaman awal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanawalWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 370.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedImage1Widget4(),
              ),
              Positioned(
                left: 46.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 55.0,
                child: GeneratedRectangle41Widget3(),
              ),
              Positioned(
                left: 48.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup105Widget4(),
              ),
              Positioned(
                left: 216.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup102Widget4(),
              ),
              Positioned(
                left: 216.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup103Widget4(),
              ),
              Positioned(
                left: 48.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup104Widget4(),
              ),
              Positioned(
                left: 47.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 168.0,
                child: GeneratedGroup9Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget30(),
              ),
              Positioned(
                left: 401.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget31(),
              ),
              Positioned(
                left: 39.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup109Widget3(),
              ),
              Positioned(
                left: 226.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup108Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup46Widget3(),
              ),
              Positioned(
                left: 65.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup88Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 25.0,
                child: GeneratedMakanTerusWidget4(),
              ),
              Positioned(
                left: 326.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 20.0,
                child: GeneratedGroup6Widget4(),
              )
            ]),
      ),
    ));
  }
}
