import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedKomentarWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedGroupWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedLine49Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedImage28Widget.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedRectangle11Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedImage4Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/Generated13KWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedLine50Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedRectangle123Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedGroup120Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedImage29Widget.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedRectangle125Widget.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedImage7Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedRectangle100Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget/generated/GeneratedKirimpesanWidget.dart';

/* Frame Komentar & Like
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKomentarLikeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 34.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 182.0,
                child:
                    GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak3(),
              ),
              Positioned(
                left: 0.0,
                top: 389.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 347.0,
                child: GeneratedRectangle11Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 56.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 700.0,
                right: null,
                bottom: null,
                width: 285.0,
                height: 20.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroupWidget3(),
              ),
              Positioned(
                left: 28.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 423.4725341796875,
                height: 1.0,
                child: GeneratedLine49Widget2(),
              ),
              Positioned(
                left: 388.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 424.3229675292969,
                height: 1.0,
                child: GeneratedLine50Widget2(),
              ),
              Positioned(
                left: 27.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 224.0,
                child: GeneratedRectangle125Widget(),
              ),
              Positioned(
                left: 350.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage7Widget3(),
              ),
              Positioned(
                left: 350.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedImage28Widget(),
              ),
              Positioned(
                left: 343.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 3.0,
                height: 1.0,
                child: GeneratedRectangle100Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 40.0,
                child: GeneratedRectangle123Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 25.0,
                child: GeneratedKomentarWidget2(),
              ),
              Positioned(
                left: 380.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage4Widget8(),
              ),
              Positioned(
                left: 350.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage29Widget(),
              ),
              Positioned(
                left: 352.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 25.0,
                child: Generated13KWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 70.0,
                child: GeneratedGroup120Widget2(),
              ),
              Positioned(
                left: 60.0,
                top: 704.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 14.0,
                child: GeneratedKirimpesanWidget(),
              )
            ]),
      ),
    ));
  }
}
