import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedGroup47Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedGroup48Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedLine38Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedImage18Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedRectangle64Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedLine37Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedDiskonLamianPalaceWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedGroup84Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedGroup94Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedLine36Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedRectangle68Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedGroup86Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedTambahkandiskonWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedImage20Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedRectangle63Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedLine35Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedRectangle61Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedRectangle67Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget2/generated/GeneratedImage15Widget9.dart';

/* Frame Manage diskon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagediskonWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle61Widget10(),
              ),
              Positioned(
                left: 87.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 45.0,
                child: GeneratedTambahkandiskonWidget1(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedImage20Widget1(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle63Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget5(),
              ),
              Positioned(
                left: 254.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 44.0,
                child: GeneratedRectangle67Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 44.0,
                child: GeneratedRectangle68Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.90716552734375,
                height: 1.0,
                child: GeneratedLine35Widget2(),
              ),
              Positioned(
                left: 190.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine36Widget2(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine37Widget2(),
              ),
              Positioned(
                left: 394.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine38Widget2(),
              ),
              Positioned(
                left: 360.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget9(),
              ),
              Positioned(
                left: 160.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup84Widget3(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup86Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage18Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 341.0,
                child: GeneratedGroup94Widget2(),
              ),
              Positioned(
                left: 249.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 49.0,
                child: GeneratedDiskonLamianPalaceWidget1(),
              )
            ]),
      ),
    ));
  }
}
