import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle42Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle46Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine41Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine37Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle47Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedTambahkanprodukdiskonWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine46Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine45Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedGroup31Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine44Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine49Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle41Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine47Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine38Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine50Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle50Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine48Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle40Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle43Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle49Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle48Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle39Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedGroup29Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle53Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine42Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle51Widget23.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle45Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedDiskonWidget10.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedGroup30Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle38Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedLine43Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget3/generated/GeneratedRectangle44Widget10.dart';

/* Frame Manage diskon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagediskonWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget3(),
              ),
              Positioned(
                left: 480.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRectangle40Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine37Widget6(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine38Widget6(),
              ),
              Positioned(
                left: 95.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle41Widget9(),
              ),
              Positioned(
                left: 95.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle43Widget10(),
              ),
              Positioned(
                left: 480.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup29Widget3(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle42Widget10(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle44Widget10(),
              ),
              Positioned(
                left: 85.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine41Widget3(),
              ),
              Positioned(
                left: 505.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine42Widget3(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine43Widget3(),
              ),
              Positioned(
                left: 1185.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine44Widget3(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine45Widget3(),
              ),
              Positioned(
                left: 1185.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine46Widget3(),
              ),
              Positioned(
                left: 1150.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup30Widget3(),
              ),
              Positioned(
                left: 1150.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup31Widget3(),
              ),
              Positioned(
                left: 875.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle49Widget9(),
              ),
              Positioned(
                left: 775.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle50Widget9(),
              ),
              Positioned(
                left: 205.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle45Widget11(),
              ),
              Positioned(
                left: 875.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle47Widget3(),
              ),
              Positioned(
                left: 105.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle46Widget4(),
              ),
              Positioned(
                left: 775.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle48Widget3(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle51Widget23(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine47Widget3(),
              ),
              Positioned(
                left: 1250.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine48Widget3(),
              ),
              Positioned(
                left: 568.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 47.0,
                child: GeneratedDiskonWidget10(),
              ),
              Positioned(
                left: 110.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedRectangle53Widget5(),
              ),
              Positioned(
                left: 180.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 98.99494934082031,
                height: 1.0,
                child: GeneratedLine49Widget6(),
              ),
              Positioned(
                left: 110.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 98.99494934082031,
                height: 1.0,
                child: GeneratedLine50Widget6(),
              ),
              Positioned(
                left: 205.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 74.0,
                child: GeneratedTambahkanprodukdiskonWidget(),
              )
            ]),
      ),
    ));
  }
}
