import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedLine22Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedLine20Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedLine19Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedGroup25Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedLine21Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedGroup9Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedkomentarlikewidget2/generated/GeneratedGroup17Widget1.dart';

/* Frame Komentar & Like
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKomentarLikeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 420.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 885.889404296875,
                height: 1.0,
                child: GeneratedLine19Widget4(),
              ),
              Positioned(
                left: 780.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 885.889404296875,
                height: 1.0,
                child: GeneratedLine20Widget4(),
              ),
              Positioned(
                left: 710.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedRectangle14Widget2(),
              ),
              Positioned(
                left: 710.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 70.71067810058594,
                height: 1.0,
                child: GeneratedLine21Widget4(),
              ),
              Positioned(
                left: 760.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 70.71067810058594,
                height: 1.0,
                child: GeneratedLine22Widget4(),
              ),
              Positioned(
                left: 10.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 670.0,
                height: 250.0,
                child: GeneratedGroup17Widget1(),
              ),
              Positioned(
                left: 780.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 500.0,
                height: 720.0,
                child: GeneratedGroup9Widget8(),
              ),
              Positioned(
                left: 10.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedGroup25Widget1(),
              )
            ]),
      ),
    ));
  }
}
