import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup106Widget1.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedCHINESEFOODWidget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedBackgroundWidget22.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup107Widget1.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedRectangle82Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedVEGETARIANWidget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup102Widget2.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedBackgroundWidget11.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup105Widget2.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup6Widget2.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup9Widget3.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedMakanTerusWidget2.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedImage1Widget2.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup103Widget2.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedJUNKFOODWidget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedBackgroundWidget23.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedGroup104Widget2.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedBackgroundWidget10.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget/generated/GeneratedSNACKWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Upload foto
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUploadfotoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 25.0,
                child: GeneratedMakanTerusWidget2(),
              ),
              Positioned(
                left: 326.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 20.0,
                child: GeneratedGroup6Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 80.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 22.0,
                child: GeneratedJUNKFOODWidget(),
              ),
              Positioned(
                left: 216.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 216.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 234.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 22.0,
                child: GeneratedCHINESEFOODWidget(),
              ),
              Positioned(
                left: 77.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 25.0,
                child: GeneratedVEGETARIANWidget(),
              ),
              Positioned(
                left: 266.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 25.0,
                child: GeneratedSNACKWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 168.0,
                child: GeneratedGroup9Widget3(),
              ),
              Positioned(
                left: null,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: TransformHelper.translate(
                    x: -200.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedBackgroundWidget10()),
              ),
              Positioned(
                left: null,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: TransformHelper.translate(
                    x: 200.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedBackgroundWidget11()),
              ),
              Positioned(
                left: 20.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 99.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 370.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedImage1Widget2(),
              ),
              Positioned(
                left: 47.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 54.0,
                child: GeneratedRectangle82Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup106Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup105Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup104Widget2(),
              ),
              Positioned(
                left: 216.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup103Widget2(),
              ),
              Positioned(
                left: 216.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup102Widget2(),
              ),
              Positioned(
                left: 47.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 168.0,
                child: GeneratedGroup107Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget22(),
              ),
              Positioned(
                left: 401.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget23(),
              ),
              Positioned(
                left: 0.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 317.0,
                child: GeneratedFrame1Widget(),
              )
            ]),
      ),
    ));
  }
}
