import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedGroup101Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedRectangle64Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedGroup47Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedRectangle125Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedGroup100Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedKebabKayanaWidget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedGroup48Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedMieCabeWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget1/generated/GeneratedImage15Widget12.dart';

/* Frame Isi kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIsikategoriWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget9(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 201.0,
                child: GeneratedGroup100Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 201.0,
                child: GeneratedGroup101Widget1(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle125Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget7(),
              ),
              Positioned(
                left: 69.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 22.0,
                child: GeneratedMieCabeWidget1(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget12(),
              ),
              Positioned(
                left: 256.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 22.0,
                child: GeneratedKebabKayanaWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget9(),
              )
            ]),
      ),
    ));
  }
}
