import 'package:flutter/material.dart';

/* Text User ----->
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''User  ----->''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 200.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
