import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget4/generated/GeneratedLine20Widget5.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget4/generated/GeneratedRectangle12Widget2.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget4/generated/GeneratedGroup9Widget9.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget4/generated/GeneratedGroup25Widget2.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget4/generated/GeneratedLine19Widget5.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget4/generated/GeneratedGroup17Widget2.dart';

/* Frame Deskripsi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeskripsiWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 420.0,
                child: GeneratedRectangle12Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 885.889404296875,
                height: 1.0,
                child: GeneratedLine19Widget5(),
              ),
              Positioned(
                left: 780.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 885.889404296875,
                height: 1.0,
                child: GeneratedLine20Widget5(),
              ),
              Positioned(
                left: 10.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 670.0,
                height: 250.0,
                child: GeneratedGroup17Widget2(),
              ),
              Positioned(
                left: 780.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 500.0,
                height: 720.0,
                child: GeneratedGroup9Widget9(),
              ),
              Positioned(
                left: 10.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedGroup25Widget2(),
              )
            ]),
      ),
    ));
  }
}
