import 'package:flutter/material.dart';

/* UndefinedNode email-id
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmailidWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
