import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedBackgroundWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup108Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedMakanTerusWidget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup88Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedBackgroundWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup105Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup103Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup109Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup102Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget/generated/GeneratedGroup104Widget.dart';

/* Frame Halaman awal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanawalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 370.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 55.0,
                child: GeneratedRectangle41Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup105Widget(),
              ),
              Positioned(
                left: 216.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup102Widget(),
              ),
              Positioned(
                left: 216.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup103Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup104Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 168.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget2(),
              ),
              Positioned(
                left: 401.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget3(),
              ),
              Positioned(
                left: 39.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup109Widget(),
              ),
              Positioned(
                left: 226.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup108Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup46Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup88Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 25.0,
                child: GeneratedMakanTerusWidget(),
              ),
              Positioned(
                left: 326.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 20.0,
                child: GeneratedGroup6Widget(),
              )
            ]),
      ),
    ));
  }
}
