import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedProfilandaWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedSimpanperubahanWidget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedBuangperubahanWidget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedImage27Widget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedZakieass_Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedRectangle141Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedRectangle138Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedRectangle144Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedKotaMalangIndonesiaWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedImage12Widget14.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedRectangle143Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedZakisetyawan2gmailcomWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedImage26Widget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedEllipse5Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedImage25Widget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedRectangle139Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofillogoutwidget/generated/GeneratedRectangle140Widget1.dart';

/* Frame CRU profil & Log-out
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCRUprofilLogoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedRectangle138Widget1(),
              ),
              Positioned(
                left: 158.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 25.0,
                child: GeneratedProfilandaWidget1(),
              ),
              Positioned(
                left: 10.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage12Widget14(),
              ),
              Positioned(
                left: 142.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedEllipse5Widget3(),
              ),
              Positioned(
                left: 112.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 30.0,
                child: GeneratedRectangle139Widget1(),
              ),
              Positioned(
                left: 82.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedRectangle140Widget1(),
              ),
              Positioned(
                left: 82.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedRectangle141Widget1(),
              ),
              Positioned(
                left: 285.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage25Widget(),
              ),
              Positioned(
                left: 305.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage26Widget(),
              ),
              Positioned(
                left: 305.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage27Widget(),
              ),
              Positioned(
                left: 147.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 25.0,
                child: GeneratedRectangle143Widget1(),
              ),
              Positioned(
                left: 147.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 25.0,
                child: GeneratedRectangle144Widget1(),
              ),
              Positioned(
                left: 156.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 17.0,
                child: GeneratedBuangperubahanWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 17.0,
                child: GeneratedSimpanperubahanWidget(),
              ),
              Positioned(
                left: 174.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 23.0,
                child: GeneratedZakieass_Widget2(),
              ),
              Positioned(
                left: 115.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 23.0,
                child: GeneratedZakisetyawan2gmailcomWidget2(),
              ),
              Positioned(
                left: 128.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 20.0,
                child: GeneratedKotaMalangIndonesiaWidget1(),
              )
            ]),
      ),
    ));
  }
}
