import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanloginwidget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanloginwidget/generated/GeneratedSigninWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanloginwidget/generated/GeneratedGroup16Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanloginwidget/generated/GeneratedIngatkankatasandiWidget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanloginwidget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanloginwidget/generated/GeneratedGroup14Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanloginwidget/generated/GeneratedRectangle29Widget.dart';

/* Frame Halaman Log-in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 290.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 700.0,
                height: 400.0,
                child: GeneratedRectangle24Widget1(),
              ),
              Positioned(
                left: 400.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 470.0,
                height: 30.0,
                child: GeneratedGroup14Widget1(),
              ),
              Positioned(
                left: 400.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 470.0,
                height: 30.0,
                child: GeneratedGroup16Widget2(),
              ),
              Positioned(
                left: 535.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 40.0,
                child: GeneratedRectangle28Widget2(),
              ),
              Positioned(
                left: 400.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 21.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 425.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 20.0,
                child: GeneratedIngatkankatasandiWidget(),
              ),
              Positioned(
                left: 577.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 47.0,
                child: GeneratedSigninWidget1(),
              )
            ]),
      ),
    ));
  }
}
