import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle48Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine50Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine48Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle40Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle51Widget21.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle44Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle46Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle43Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine44Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine37Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedGroup29Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine41Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine43Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle49Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine47Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedGroup31Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine45Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle41Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedKategoriWidget15.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedTambahkankategoriWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle38Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedGroup30Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle53Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine38Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle42Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle50Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle47Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedRectangle45Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine49Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine42Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget3/generated/GeneratedLine46Widget1.dart';

/* Frame Manage kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagekategoriWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget1(),
              ),
              Positioned(
                left: 480.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRectangle40Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine37Widget4(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine38Widget4(),
              ),
              Positioned(
                left: 95.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle41Widget7(),
              ),
              Positioned(
                left: 95.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle43Widget8(),
              ),
              Positioned(
                left: 480.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup29Widget1(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle42Widget8(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle44Widget8(),
              ),
              Positioned(
                left: 85.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine41Widget1(),
              ),
              Positioned(
                left: 505.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine42Widget1(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine43Widget1(),
              ),
              Positioned(
                left: 1185.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine44Widget1(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine45Widget1(),
              ),
              Positioned(
                left: 1185.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine46Widget1(),
              ),
              Positioned(
                left: 1150.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup30Widget1(),
              ),
              Positioned(
                left: 1150.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup31Widget1(),
              ),
              Positioned(
                left: 875.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle49Widget7(),
              ),
              Positioned(
                left: 775.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle50Widget7(),
              ),
              Positioned(
                left: 205.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle45Widget9(),
              ),
              Positioned(
                left: 875.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle47Widget1(),
              ),
              Positioned(
                left: 105.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle46Widget2(),
              ),
              Positioned(
                left: 775.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle48Widget1(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle51Widget21(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine47Widget1(),
              ),
              Positioned(
                left: 1250.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine48Widget1(),
              ),
              Positioned(
                left: 567.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget15(),
              ),
              Positioned(
                left: 110.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedRectangle53Widget3(),
              ),
              Positioned(
                left: 180.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 98.99494934082031,
                height: 1.0,
                child: GeneratedLine49Widget4(),
              ),
              Positioned(
                left: 110.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 98.99494934082031,
                height: 1.0,
                child: GeneratedLine50Widget4(),
              ),
              Positioned(
                left: 190.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 89.0,
                child: GeneratedTambahkankategoriWidget3(),
              )
            ]),
      ),
    ));
  }
}
