import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedLine55Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedLine56Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedLine20Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedLine54Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedLine19Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedLine22Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedRectangle60Widget14.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedRectangle59Widget33.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedLine21Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedGroup9Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget2/generated/GeneratedLine53Widget.dart';

/* Frame Manage komentar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagekomentarWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 420.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 885.889404296875,
                height: 1.0,
                child: GeneratedLine19Widget3(),
              ),
              Positioned(
                left: 780.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 885.889404296875,
                height: 1.0,
                child: GeneratedLine20Widget3(),
              ),
              Positioned(
                left: 710.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 710.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 70.71067810058594,
                height: 1.0,
                child: GeneratedLine21Widget3(),
              ),
              Positioned(
                left: 760.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 70.71067810058594,
                height: 1.0,
                child: GeneratedLine22Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 670.0,
                height: 250.0,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 780.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 500.0,
                height: 720.0,
                child: GeneratedGroup9Widget7(),
              ),
              Positioned(
                left: 833.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle59Widget33(),
              ),
              Positioned(
                left: 870.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 45.0,
                child: GeneratedRectangle60Widget14(),
              ),
              Positioned(
                left: 870.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 195.25624084472656,
                height: 1.0,
                child: GeneratedLine53Widget(),
              ),
              Positioned(
                left: 870.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 195.0281982421875,
                height: 1.0,
                child: GeneratedLine54Widget(),
              ),
              Positioned(
                left: 863.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 42.42640686035156,
                height: 1.0,
                child: GeneratedLine55Widget(),
              ),
              Positioned(
                left: 833.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 42.42640686035156,
                height: 1.0,
                child: GeneratedLine56Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 50.0,
                child: GeneratedGroup25Widget(),
              )
            ]),
      ),
    ));
  }
}
