import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedImage4Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedKomentarWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedGroupWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedGroup120Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedImage7Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedGroup112Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/Generated13KWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedRectangle100Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedLine50Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedImage9Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedLine49Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedRectangle123Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekomentarwidget1/generated/GeneratedRectangle91Widget3.dart';

/* Frame Manage komentar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagekomentarWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 74.0,
                child:
                    GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak2(),
              ),
              Positioned(
                left: 0.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 347.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroupWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 423.4725341796875,
                height: 1.0,
                child: GeneratedLine49Widget1(),
              ),
              Positioned(
                left: 388.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 424.3229675292969,
                height: 1.0,
                child: GeneratedLine50Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 224.0,
                child: GeneratedRectangle91Widget3(),
              ),
              Positioned(
                left: 343.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 3.0,
                height: 1.0,
                child: GeneratedRectangle100Widget1(),
              ),
              Positioned(
                left: 350.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage9Widget2(),
              ),
              Positioned(
                left: 350.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage7Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 40.0,
                child: GeneratedRectangle123Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 25.0,
                child: GeneratedKomentarWidget1(),
              ),
              Positioned(
                left: 380.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage4Widget6(),
              ),
              Positioned(
                left: 352.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 25.0,
                child: Generated13KWidget2(),
              ),
              Positioned(
                left: 10.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 70.0,
                child: GeneratedGroup120Widget1(),
              ),
              Positioned(
                left: 50.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 30.0,
                child: GeneratedGroup112Widget(),
              )
            ]),
      ),
    ));
  }
}
