import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedKebabKayanaWidget9.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedMieCabeWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedRectangle64Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedGroup101Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedGroup100Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedGroup47Widget13.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedRectangle91Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedGroup48Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget2/generated/GeneratedImage15Widget13.dart';

/* Frame Isi kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIsikategoriWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget11(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 201.0,
                child: GeneratedGroup100Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 201.0,
                child: GeneratedGroup101Widget2(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle91Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget9(),
              ),
              Positioned(
                left: 69.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 22.0,
                child: GeneratedMieCabeWidget2(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget13(),
              ),
              Positioned(
                left: 256.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 22.0,
                child: GeneratedKebabKayanaWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget13(),
              )
            ]),
      ),
    ));
  }
}
