import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle39Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle71Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle67Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedEllipse3Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedLine59Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedLogoutWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle40Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle38Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedLine60Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedProfilAndaWidget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedLine57Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedEditProfilWidget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle70Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle72Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedLine58Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle69Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget2/generated/GeneratedRectangle68Widget3.dart';

/* Frame profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget9(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget9(),
              ),
              Positioned(
                left: 480.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRectangle40Widget9(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine57Widget(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine58Widget(),
              ),
              Positioned(
                left: 546.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 44.0,
                child: GeneratedProfilAndaWidget(),
              ),
              Positioned(
                left: 290.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 700.0,
                height: 450.0,
                child: GeneratedRectangle71Widget(),
              ),
              Positioned(
                left: 540.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedEllipse3Widget3(),
              ),
              Positioned(
                left: 515.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 20.0,
                child: GeneratedRectangle67Widget3(),
              ),
              Positioned(
                left: 465.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 20.0,
                child: GeneratedRectangle68Widget3(),
              ),
              Positioned(
                left: 570.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 197.98989868164062,
                height: 1.0,
                child: GeneratedLine59Widget(),
              ),
              Positioned(
                left: 710.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 197.98989868164062,
                height: 1.0,
                child: GeneratedLine60Widget(),
              ),
              Positioned(
                left: 465.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 20.0,
                child: GeneratedRectangle69Widget1(),
              ),
              Positioned(
                left: 591.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle70Widget(),
              ),
              Positioned(
                left: 591.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle72Widget(),
              ),
              Positioned(
                left: 605.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 20.0,
                child: GeneratedEditProfilWidget(),
              ),
              Positioned(
                left: 611.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 23.0,
                child: GeneratedLogoutWidget2(),
              )
            ]),
      ),
    ));
  }
}
