import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedsukawidget/generated/GeneratedImage12Widget26.dart';
import 'package:flutterapp/makanterusapp/generatedsukawidget/generated/GeneratedLine82Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedsukawidget/generated/GeneratedSukaWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedsukawidget/generated/GeneratedKebabKayanaWidget10.dart';
import 'package:flutterapp/makanterusapp/generatedsukawidget/generated/GeneratedRectangle158Widget.dart';
import 'package:flutterapp/makanterusapp/generatedsukawidget/generated/GeneratedLine81Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedsukawidget/generated/GeneratedRectangle125Widget3.dart';

/* Frame suka
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSukaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedRectangle158Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage12Widget26(),
              ),
              Positioned(
                left: 184.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 31.0,
                child: GeneratedSukaWidget1(),
              ),
              Positioned(
                left: 107.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 100.0,
                child: GeneratedRectangle125Widget3(),
              ),
              Positioned(
                left: 156.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 22.0,
                child: GeneratedKebabKayanaWidget10(),
              ),
              Positioned(
                left: 32.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine81Widget2(),
              ),
              Positioned(
                left: 32.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine82Widget2(),
              )
            ]),
      ),
    ));
  }
}
