import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedZakieass_Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedRectangle140Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedProfilandaWidget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedEditprofilWidget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedRectangle138Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedImage12Widget13.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedKotaMalangIndonesiaWidget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedRectangle141Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedRectangle144Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedZakisetyawan2gmailcomWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedRectangle143Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedLogoutWidget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedRectangle139Widget.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget/generated/GeneratedEllipse4Widget.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedRectangle138Widget(),
              ),
              Positioned(
                left: 158.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 25.0,
                child: GeneratedProfilandaWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage12Widget13(),
              ),
              Positioned(
                left: 142.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 30.0,
                child: GeneratedRectangle139Widget(),
              ),
              Positioned(
                left: 82.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedRectangle140Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 23.0,
                child: GeneratedZakisetyawan2gmailcomWidget1(),
              ),
              Positioned(
                left: 82.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedRectangle141Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 25.0,
                child: GeneratedRectangle143Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 25.0,
                child: GeneratedRectangle144Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 23.0,
                child: GeneratedLogoutWidget(),
              ),
              Positioned(
                left: 174.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 23.0,
                child: GeneratedZakieass_Widget1(),
              ),
              Positioned(
                left: 175.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 20.0,
                child: GeneratedEditprofilWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 20.0,
                child: GeneratedKotaMalangIndonesiaWidget(),
              )
            ]),
      ),
    ));
  }
}
