import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedGroup94Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedRectangle64Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedLine35Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedLine36Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedRectangle63Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedImage18Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedGroup86Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedImage15Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedRectangle67Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedRectangle61Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedLine37Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedGroup48Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedRectangle68Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedGroup84Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedGroup47Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedTambahkanprodukteratasWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedLine38Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedRectangle69Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget2/generated/GeneratedAyamCrispyWidget3.dart';

/* Frame Manage produk teratas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManageprodukteratasWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle61Widget9(),
              ),
              Positioned(
                left: 75.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 42.0,
                child: GeneratedTambahkanprodukteratasWidget1(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle69Widget(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle63Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget4(),
              ),
              Positioned(
                left: 260.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 23.0,
                child: GeneratedAyamCrispyWidget3(),
              ),
              Positioned(
                left: 254.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 44.0,
                child: GeneratedRectangle67Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 44.0,
                child: GeneratedRectangle68Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.90716552734375,
                height: 1.0,
                child: GeneratedLine35Widget1(),
              ),
              Positioned(
                left: 190.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine36Widget1(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine37Widget1(),
              ),
              Positioned(
                left: 394.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine38Widget1(),
              ),
              Positioned(
                left: 360.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget8(),
              ),
              Positioned(
                left: 160.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup84Widget2(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup86Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage18Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 341.0,
                child: GeneratedGroup94Widget1(),
              )
            ]),
      ),
    ));
  }
}
