import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine9Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle66Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine12Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine7Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedGroup12Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle63Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine5Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedGroup11Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine8Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedGroup54Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle65Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle62Widget19.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle64Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedGroup13Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine10Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine74Widget.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine73Widget.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle88Widget.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedGroup55Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle61Widget24.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine6Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedKategoriWidget9.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget3/generated/GeneratedLine11Widget2.dart';

/* Frame Bahasa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBahasaWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine5Widget4(),
              ),
              Positioned(
                left: 16.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine6Widget3(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget9(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine7Widget2(),
              ),
              Positioned(
                left: 336.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine8Widget2(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine9Widget2(),
              ),
              Positioned(
                left: 656.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine10Widget2(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine11Widget2(),
              ),
              Positioned(
                left: 976.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine12Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedGroup11Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 611.0,
                height: 324.0,
                child: GeneratedGroup12Widget2(),
              ),
              Positioned(
                left: 656.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 610.0,
                height: 324.0,
                child: GeneratedGroup13Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle61Widget24(),
              ),
              Positioned(
                left: 336.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle62Widget19(),
              ),
              Positioned(
                left: 180.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle65Widget2(),
              ),
              Positioned(
                left: 816.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle66Widget2(),
              ),
              Positioned(
                left: 656.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle63Widget9(),
              ),
              Positioned(
                left: 976.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle64Widget12(),
              ),
              Positioned(
                left: 250.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 450.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 250.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 60.0,
                child: GeneratedGroup55Widget2(),
              ),
              Positioned(
                left: 395.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 490.0,
                height: 320.0,
                child: GeneratedGroup54Widget2(),
              ),
              Positioned(
                left: 990.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle88Widget(),
              ),
              Positioned(
                left: 990.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 42.42640686035156,
                height: 1.0,
                child: GeneratedLine73Widget(),
              ),
              Positioned(
                left: 1020.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 42.42640686035156,
                height: 1.0,
                child: GeneratedLine74Widget(),
              )
            ]),
      ),
    ));
  }
}
