import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedImage17Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedRectangle61Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedImage18Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedRectangle62Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedRectangle64Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedBakmieGorengWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedGroup48Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedImage16Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedGroup47Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedMieWarmindoWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedTambahkanprodukteratasWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedRectangle63Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedAyamCrispyWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanageprodukterataswidget1/generated/GeneratedImage15Widget5.dart';

/* Frame Manage produk teratas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManageprodukteratasWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle61Widget4(),
              ),
              Positioned(
                left: 75.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 42.0,
                child: GeneratedTambahkanprodukteratasWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle62Widget3(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle63Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget2(),
              ),
              Positioned(
                left: 360.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget5(),
              ),
              Positioned(
                left: 160.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage16Widget1(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage17Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage18Widget1(),
              ),
              Positioned(
                left: 260.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 23.0,
                child: GeneratedAyamCrispyWidget2(),
              ),
              Positioned(
                left: 49.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 23.0,
                child: GeneratedMieWarmindoWidget2(),
              ),
              Positioned(
                left: 250.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 23.0,
                child: GeneratedBakmieGorengWidget(),
              )
            ]),
      ),
    ));
  }
}
