import 'package:flutter/material.dart';

/* UndefinedNode nama pengguna
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNamapenggunaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
