import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle67Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedLine59Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle70Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle38Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle68Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle40Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle69Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedLine57Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedSimpanperubahanWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedProfilAndaWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedLine60Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedLine58Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedBuangperubahanWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle72Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle39Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedEllipse3Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedcruprofilwidget/generated/GeneratedRectangle71Widget2.dart';

/* Frame CRU profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCRUprofilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget11(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget11(),
              ),
              Positioned(
                left: 480.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRectangle40Widget11(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine57Widget2(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine58Widget2(),
              ),
              Positioned(
                left: 546.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 44.0,
                child: GeneratedProfilAndaWidget2(),
              ),
              Positioned(
                left: 290.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 700.0,
                height: 450.0,
                child: GeneratedRectangle71Widget2(),
              ),
              Positioned(
                left: 591.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle72Widget2(),
              ),
              Positioned(
                left: 591.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle70Widget2(),
              ),
              Positioned(
                left: 594.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 14.0,
                child: GeneratedSimpanperubahanWidget2(),
              ),
              Positioned(
                left: 597.0,
                top: 599.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 14.0,
                child: GeneratedBuangperubahanWidget2(),
              ),
              Positioned(
                left: 540.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedEllipse3Widget5(),
              ),
              Positioned(
                left: 515.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 20.0,
                child: GeneratedRectangle67Widget5(),
              ),
              Positioned(
                left: 465.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 20.0,
                child: GeneratedRectangle68Widget5(),
              ),
              Positioned(
                left: 570.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 197.98989868164062,
                height: 1.0,
                child: GeneratedLine59Widget2(),
              ),
              Positioned(
                left: 710.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 197.98989868164062,
                height: 1.0,
                child: GeneratedLine60Widget2(),
              ),
              Positioned(
                left: 465.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 20.0,
                child: GeneratedRectangle69Widget3(),
              ),
              Positioned(
                left: 680.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 745.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedGroup22Widget(),
              ),
              Positioned(
                left: 795.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedGroup23Widget(),
              ),
              Positioned(
                left: 795.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedGroup24Widget(),
              )
            ]),
      ),
    ));
  }
}
