import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup102Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedBackgroundWidget6.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup103Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedBackgroundWidget7.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup106Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup105Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup109Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedMakanTerusWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup104Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup108Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup107Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup114Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget/generated/GeneratedGroup46Widget1.dart';

/* Frame Pilihan menu admin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPilihanmenuadminWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 25.0,
                child: GeneratedMakanTerusWidget1(),
              ),
              Positioned(
                left: 326.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 20.0,
                child: GeneratedGroup6Widget1(),
              ),
              Positioned(
                left: 370.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedImage1Widget1(),
              ),
              Positioned(
                left: 46.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 55.0,
                child: GeneratedRectangle41Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup105Widget1(),
              ),
              Positioned(
                left: 216.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup102Widget1(),
              ),
              Positioned(
                left: 216.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup103Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup104Widget1(),
              ),
              Positioned(
                left: 47.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 168.0,
                child: GeneratedGroup107Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget6(),
              ),
              Positioned(
                left: 401.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget7(),
              ),
              Positioned(
                left: 39.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup109Widget1(),
              ),
              Positioned(
                left: 226.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup108Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup46Widget1(),
              ),
              Positioned(
                left: 65.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup106Widget(),
              ),
              Positioned(
                left: 260.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 140.0,
                child: GeneratedGroup114Widget(),
              )
            ]),
      ),
    ));
  }
}
