import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup108Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedBackgroundWidget39.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup88Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedRectangle154Widget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedSigninWidget.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedBackgroundWidget38.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedRectangle41Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup105Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup6Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup102Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup109Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup9Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedMakanTerusWidget6.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup46Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup103Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedhalamanawalwidget2/generated/GeneratedGroup104Widget6.dart';

/* Frame Halaman awal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanawalWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 46.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 55.0,
                child: GeneratedRectangle41Widget5(),
              ),
              Positioned(
                left: 48.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup105Widget6(),
              ),
              Positioned(
                left: 216.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup102Widget6(),
              ),
              Positioned(
                left: 216.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup103Widget6(),
              ),
              Positioned(
                left: 48.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup104Widget6(),
              ),
              Positioned(
                left: 47.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 168.0,
                child: GeneratedGroup9Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget38(),
              ),
              Positioned(
                left: 401.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget39(),
              ),
              Positioned(
                left: 39.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup109Widget5(),
              ),
              Positioned(
                left: 226.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup108Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup46Widget5(),
              ),
              Positioned(
                left: 65.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup88Widget2(),
              ),
              Positioned(
                left: 25.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 25.0,
                child: GeneratedMakanTerusWidget6(),
              ),
              Positioned(
                left: 310.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 20.0,
                child: GeneratedGroup6Widget6(),
              ),
              Positioned(
                left: 350.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 20.0,
                child: GeneratedRectangle154Widget(),
              ),
              Positioned(
                left: 355.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 20.0,
                child: GeneratedSigninWidget(),
              )
            ]),
      ),
    ));
  }
}
