import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedLogoutWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedZakieass_Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedRectangle143Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedRectangle139Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedProfilandaWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedRectangle138Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedEllipse4Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedEditprofilWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedZakisetyawan2gmailcomWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedImage12Widget17.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedRectangle144Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedRectangle141Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedKotaMalangIndonesiaWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedprofilwidget1/generated/GeneratedRectangle140Widget2.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedRectangle138Widget2(),
              ),
              Positioned(
                left: 158.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 25.0,
                child: GeneratedProfilandaWidget2(),
              ),
              Positioned(
                left: 10.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage12Widget17(),
              ),
              Positioned(
                left: 142.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedEllipse4Widget1(),
              ),
              Positioned(
                left: 112.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 30.0,
                child: GeneratedRectangle139Widget2(),
              ),
              Positioned(
                left: 82.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedRectangle140Widget2(),
              ),
              Positioned(
                left: 115.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 23.0,
                child: GeneratedZakisetyawan2gmailcomWidget3(),
              ),
              Positioned(
                left: 82.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 30.0,
                child: GeneratedRectangle141Widget2(),
              ),
              Positioned(
                left: 157.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 25.0,
                child: GeneratedRectangle143Widget2(),
              ),
              Positioned(
                left: 157.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 25.0,
                child: GeneratedRectangle144Widget2(),
              ),
              Positioned(
                left: 180.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 23.0,
                child: GeneratedLogoutWidget1(),
              ),
              Positioned(
                left: 174.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 23.0,
                child: GeneratedZakieass_Widget3(),
              ),
              Positioned(
                left: 175.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 20.0,
                child: GeneratedEditprofilWidget1(),
              ),
              Positioned(
                left: 128.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 20.0,
                child: GeneratedKotaMalangIndonesiaWidget2(),
              )
            ]),
      ),
    ));
  }
}
