import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedKebabKayanaWidget.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedRectangle64Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedGroup47Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedImage15Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedGroup84Widget.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedRectangle91Widget.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedMieCabeWidget.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedGroup48Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedGroup101Widget.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget/generated/GeneratedGroup100Widget.dart';

/* Frame Isi kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIsikategoriWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget1(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 201.0,
                child: GeneratedGroup100Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 201.0,
                child: GeneratedGroup101Widget(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle91Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 22.0,
                child: GeneratedMieCabeWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup84Widget(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget4(),
              ),
              Positioned(
                left: 259.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 22.0,
                child: GeneratedKebabKayanaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget1(),
              )
            ]),
      ),
    ));
  }
}
