import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedRectangle51Widget27.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedRectangle113Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedLine38Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedManageuserWidget5.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedRectangle93Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedRectangle40Widget13.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedRectangle115Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedGroup57Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedRectangle39Widget13.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedLine37Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedRectangle114Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedLine47Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedRectangle112Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanageuserwidget4/generated/GeneratedLine48Widget7.dart';

/* Frame Manage user
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManageuserWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedRectangle93Widget(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle51Widget27(),
              ),
              Positioned(
                left: 468.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 60.0,
                child: GeneratedRectangle40Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget13(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine37Widget12(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine38Widget12(),
              ),
              Positioned(
                left: 1250.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine48Widget7(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine47Widget8(),
              ),
              Positioned(
                left: 529.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 44.0,
                child: GeneratedManageuserWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 1240.0,
                height: 520.0,
                child: GeneratedGroup57Widget3(),
              ),
              Positioned(
                left: 851.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 40.0,
                child: GeneratedRectangle112Widget6(),
              ),
              Positioned(
                left: 433.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 40.0,
                child: GeneratedRectangle113Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 40.0,
                child: GeneratedRectangle114Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 40.0,
                child: GeneratedRectangle115Widget1(),
              )
            ]),
      ),
    ));
  }
}
