import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine11Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedGroup13Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle83Widget3.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine8Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedDetailWidget1.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedGroup12Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle31Widget3.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle80Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle77Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedUploadfotoWidget4.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine12Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle78Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle81Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle6Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedKategoriWidget14.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle8Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine7Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine5Widget9.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine70Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine6Widget8.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedGroup11Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle9Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle79Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine10Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine69Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine31Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle82Widget1.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine9Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedLine32Widget.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle7Widget7.dart';
import 'package:flutterapp/makanterusapp/generateduploadfotowidget3/generated/GeneratedRectangle84Widget3.dart';

/* Frame upload foto
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUploadfotoWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle6Widget7(),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine5Widget9(),
              ),
              Positioned(
                left: 16.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine6Widget8(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle7Widget7(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle8Widget7(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle9Widget7(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget14(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine7Widget7(),
              ),
              Positioned(
                left: 336.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine8Widget7(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine9Widget7(),
              ),
              Positioned(
                left: 656.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine10Widget7(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine11Widget7(),
              ),
              Positioned(
                left: 976.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine12Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedGroup11Widget7(),
              ),
              Positioned(
                left: 19.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 611.0,
                height: 324.0,
                child: GeneratedGroup12Widget7(),
              ),
              Positioned(
                left: 656.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 610.0,
                height: 324.0,
                child: GeneratedGroup13Widget7(),
              ),
              Positioned(
                left: 250.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 450.0,
                child: GeneratedRectangle31Widget3(),
              ),
              Positioned(
                left: 250.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 80.0,
                child: GeneratedRectangle32Widget(),
              ),
              Positioned(
                left: 975.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 975.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 55.865909576416016,
                height: 1.0,
                child: GeneratedLine31Widget(),
              ),
              Positioned(
                left: 1015.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 55.865909576416016,
                height: 1.0,
                child: GeneratedLine32Widget(),
              ),
              Positioned(
                left: 270.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 38.0,
                child: GeneratedUploadfotoWidget4(),
              ),
              Positioned(
                left: 270.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 35.0,
                child: GeneratedDetailWidget1(),
              ),
              Positioned(
                left: 270.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 60.0,
                child: GeneratedRectangle77Widget(),
              ),
              Positioned(
                left: 270.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 60.0,
                child: GeneratedRectangle78Widget(),
              ),
              Positioned(
                left: 270.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 80.0,
                child: GeneratedRectangle83Widget3(),
              ),
              Positioned(
                left: 270.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 20.0,
                child: GeneratedRectangle79Widget(),
              ),
              Positioned(
                left: 270.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 20.0,
                child: GeneratedRectangle80Widget(),
              ),
              Positioned(
                left: 270.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 20.0,
                child: GeneratedRectangle84Widget3(),
              ),
              Positioned(
                left: 680.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 240.0,
                child: GeneratedRectangle81Widget(),
              ),
              Positioned(
                left: 680.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 408.0440979003906,
                height: 1.0,
                child: GeneratedLine69Widget(),
              ),
              Positioned(
                left: 1007.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 405.6217346191406,
                height: 1.0,
                child: GeneratedLine70Widget(),
              ),
              Positioned(
                left: 755.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 30.0,
                child: GeneratedRectangle82Widget1(),
              )
            ]),
      ),
    ));
  }
}
