import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle43Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine45Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine37Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle46Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle47Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine44Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle46Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle45Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle49Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle38Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine40Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine38Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle39Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine39Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine43Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle44Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle40Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedJunkFoodWidget15.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle48Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle42Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle45Widget13.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine41Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine46Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedLine42Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle50Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget16/generated/GeneratedRectangle41Widget10.dart';

/* Frame Kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKategoriWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget4(),
              ),
              Positioned(
                left: 480.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRectangle40Widget4(),
              ),
              Positioned(
                left: 552.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 44.0,
                child: GeneratedJunkFoodWidget15(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine37Widget7(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine38Widget7(),
              ),
              Positioned(
                left: 95.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle41Widget10(),
              ),
              Positioned(
                left: 95.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle43Widget11(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle42Widget11(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle44Widget11(),
              ),
              Positioned(
                left: 95.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine39Widget1(),
              ),
              Positioned(
                left: 515.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine40Widget1(),
              ),
              Positioned(
                left: 85.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine41Widget4(),
              ),
              Positioned(
                left: 505.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine42Widget4(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine43Widget4(),
              ),
              Positioned(
                left: 1185.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine44Widget4(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine45Widget4(),
              ),
              Positioned(
                left: 1185.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine46Widget4(),
              ),
              Positioned(
                left: 205.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle45Widget12(),
              ),
              Positioned(
                left: 875.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle49Widget10(),
              ),
              Positioned(
                left: 105.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 403.0,
                height: 10.0,
                child: GeneratedRectangle46Widget5(),
              ),
              Positioned(
                left: 775.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle50Widget10(),
              ),
              Positioned(
                left: 205.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle45Widget13(),
              ),
              Positioned(
                left: 875.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle47Widget4(),
              ),
              Positioned(
                left: 105.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle46Widget6(),
              ),
              Positioned(
                left: 775.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle48Widget4(),
              ),
              Positioned(
                left: 1110.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 36.0,
                child: GeneratedGroup18Widget(),
              )
            ]),
      ),
    ));
  }
}
