import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedGroup13Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle61Widget25.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine74Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine11Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine7Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle7Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle88Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedGroup54Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle63Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine5Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedGroup12Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine73Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle64Widget13.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle66Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedGroup55Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine6Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle65Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine10Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine8Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle9Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine12Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedGroup11Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedLine9Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedRectangle62Widget20.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget4/generated/GeneratedKategoriWidget10.dart';

/* Frame Bahasa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBahasaWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle6Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine5Widget5(),
              ),
              Positioned(
                left: 16.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine6Widget4(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle7Widget3(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle8Widget3(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle9Widget3(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget10(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine7Widget3(),
              ),
              Positioned(
                left: 336.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine8Widget3(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine9Widget3(),
              ),
              Positioned(
                left: 656.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine10Widget3(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine11Widget3(),
              ),
              Positioned(
                left: 976.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine12Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedGroup11Widget3(),
              ),
              Positioned(
                left: 19.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 611.0,
                height: 324.0,
                child: GeneratedGroup12Widget3(),
              ),
              Positioned(
                left: 656.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 610.0,
                height: 324.0,
                child: GeneratedGroup13Widget3(),
              ),
              Positioned(
                left: 19.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle61Widget25(),
              ),
              Positioned(
                left: 336.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle62Widget20(),
              ),
              Positioned(
                left: 180.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle65Widget3(),
              ),
              Positioned(
                left: 816.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle66Widget3(),
              ),
              Positioned(
                left: 656.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle63Widget10(),
              ),
              Positioned(
                left: 976.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle64Widget13(),
              ),
              Positioned(
                left: 250.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 450.0,
                child: GeneratedRectangle31Widget1(),
              ),
              Positioned(
                left: 250.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 60.0,
                child: GeneratedGroup55Widget3(),
              ),
              Positioned(
                left: 395.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 490.0,
                height: 320.0,
                child: GeneratedGroup54Widget3(),
              ),
              Positioned(
                left: 990.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle88Widget1(),
              ),
              Positioned(
                left: 990.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 42.42640686035156,
                height: 1.0,
                child: GeneratedLine73Widget1(),
              ),
              Positioned(
                left: 1020.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 42.42640686035156,
                height: 1.0,
                child: GeneratedLine74Widget1(),
              )
            ]),
      ),
    ));
  }
}
