import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedVegetarianWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedImage18Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedRectangle63Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedTambahkankategoriWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedImage15Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedJunkFoodWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedImage17Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedRectangle64Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedImage16Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedRectangle62Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedRectangle61Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget1/generated/GeneratedSnackWidget2.dart';

/* Frame Manage kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagekategoriWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle61Widget1(),
              ),
              Positioned(
                left: 80.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 45.0,
                child: GeneratedTambahkankategoriWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle62Widget(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle63Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget(),
              ),
              Positioned(
                left: 360.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage17Widget(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage16Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage18Widget(),
              ),
              Positioned(
                left: 265.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 22.0,
                child: GeneratedJunkFoodWidget2(),
              ),
              Positioned(
                left: 75.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 25.0,
                child: GeneratedSnackWidget2(),
              ),
              Positioned(
                left: 263.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 25.0,
                child: GeneratedVegetarianWidget2(),
              )
            ]),
      ),
    ));
  }
}
