import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget/generated/Generated13KWidget.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget/generated/GeneratedImage9Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget/generated/GeneratedRectangle91Widget1.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget/generated/GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget/generated/GeneratedGroup47Widget7.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget/generated/GeneratedGroupWidget.dart';

/* Frame Deskripsi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeskripsiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroupWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 224.0,
                child: GeneratedRectangle91Widget1(),
              ),
              Positioned(
                left: 350.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage7Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 182.0,
                child:
                    GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget7(),
              ),
              Positioned(
                left: 350.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage9Widget(),
              ),
              Positioned(
                left: 352.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 25.0,
                child: Generated13KWidget(),
              )
            ]),
      ),
    ));
  }
}
