import 'package:flutter/material.dart';

/* UndefinedNode PW
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPWWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
