import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedGroup11Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle64Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedLine5Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedLine8Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedLine9Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedLine6Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle62Widget18.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedGroup13Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle65Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedLine7Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedLine10Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedGroup12Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle61Widget23.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle63Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedKategoriWidget8.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedLine12Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedLine11Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedtampilanawalwidget/generated/GeneratedRectangle66Widget1.dart';

/* Frame Tampilan awal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTampilanawalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine5Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine6Widget2(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget8(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine7Widget1(),
              ),
              Positioned(
                left: 336.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine8Widget1(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine9Widget1(),
              ),
              Positioned(
                left: 656.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine10Widget1(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine11Widget1(),
              ),
              Positioned(
                left: 976.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine12Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedGroup11Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 611.0,
                height: 324.0,
                child: GeneratedGroup12Widget1(),
              ),
              Positioned(
                left: 656.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 610.0,
                height: 324.0,
                child: GeneratedGroup13Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle61Widget23(),
              ),
              Positioned(
                left: 336.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle62Widget18(),
              ),
              Positioned(
                left: 180.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle65Widget1(),
              ),
              Positioned(
                left: 816.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle66Widget1(),
              ),
              Positioned(
                left: 656.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle63Widget8(),
              ),
              Positioned(
                left: 976.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle64Widget11(),
              )
            ]),
      ),
    ));
  }
}
