import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedAdarekomendasimakananbautandaSegeralihatsekarangWidget.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedNotifikasiWidget1.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedImage12Widget24.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedAdaaktivitasmasukkeakunandazakieass_dariperangkatbarupa.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedLine82Widget.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedImage31Widget.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedImage30Widget.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedLine83Widget.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedLine81Widget.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget/generated/GeneratedRectangle157Widget.dart';

/* Frame notifikasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotifikasiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedRectangle157Widget(),
              ),
              Positioned(
                left: 162.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 31.0,
                child: GeneratedNotifikasiWidget1(),
              ),
              Positioned(
                left: 10.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage12Widget24(),
              ),
              Positioned(
                left: 70.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage30Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage31Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 41.0,
                child:
                    GeneratedAdaaktivitasmasukkeakunandazakieass_dariperangkatbarupa(),
              ),
              Positioned(
                left: 32.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine81Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine82Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine83Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 28.0,
                child:
                    GeneratedAdarekomendasimakananbautandaSegeralihatsekarangWidget(),
              )
            ]),
      ),
    ));
  }
}
