import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget2/generated/GeneratedGroupWidget4.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget2/generated/GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak4.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget2/generated/GeneratedImage29Widget1.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget2/generated/GeneratedGroup47Widget10.dart';
import 'package:flutterapp/makanterusapp/generateddeskripsiwidget2/generated/GeneratedRectangle91Widget4.dart';

/* Frame Deskripsi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeskripsiWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroupWidget4(),
              ),
              Positioned(
                left: 28.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 224.0,
                child: GeneratedRectangle91Widget4(),
              ),
              Positioned(
                left: 34.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 182.0,
                child:
                    GeneratedKebabadalahhidangandagingyangdimasakdenganasalusulmasak4(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget10(),
              ),
              Positioned(
                left: 350.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage29Widget1(),
              )
            ]),
      ),
    ));
  }
}
