import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine73Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle88Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine9Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine5Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine11Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle61Widget26.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedGroup11Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedKategoriWidget11.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle8Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine7Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle7Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedGroup12Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle31Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle65Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine8Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle6Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine12Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle66Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedGroup55Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine74Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle62Widget21.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle64Widget14.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine10Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle9Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedGroup54Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedRectangle63Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedGroup13Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget5/generated/GeneratedLine6Widget5.dart';

/* Frame Bahasa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBahasaWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle6Widget4(),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine5Widget6(),
              ),
              Positioned(
                left: 16.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine6Widget5(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle7Widget4(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle8Widget4(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle9Widget4(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget11(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine7Widget4(),
              ),
              Positioned(
                left: 336.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine8Widget4(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine9Widget4(),
              ),
              Positioned(
                left: 656.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine10Widget4(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine11Widget4(),
              ),
              Positioned(
                left: 976.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine12Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedGroup11Widget4(),
              ),
              Positioned(
                left: 19.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 611.0,
                height: 324.0,
                child: GeneratedGroup12Widget4(),
              ),
              Positioned(
                left: 656.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 610.0,
                height: 324.0,
                child: GeneratedGroup13Widget4(),
              ),
              Positioned(
                left: 19.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle61Widget26(),
              ),
              Positioned(
                left: 336.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle62Widget21(),
              ),
              Positioned(
                left: 180.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle65Widget4(),
              ),
              Positioned(
                left: 816.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle66Widget4(),
              ),
              Positioned(
                left: 656.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle63Widget11(),
              ),
              Positioned(
                left: 976.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle64Widget14(),
              ),
              Positioned(
                left: 250.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 450.0,
                child: GeneratedRectangle31Widget2(),
              ),
              Positioned(
                left: 250.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 780.0,
                height: 60.0,
                child: GeneratedGroup55Widget4(),
              ),
              Positioned(
                left: 395.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 490.0,
                height: 320.0,
                child: GeneratedGroup54Widget4(),
              ),
              Positioned(
                left: 990.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle88Widget2(),
              ),
              Positioned(
                left: 990.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 42.42640686035156,
                height: 1.0,
                child: GeneratedLine73Widget2(),
              ),
              Positioned(
                left: 1020.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 42.42640686035156,
                height: 1.0,
                child: GeneratedLine74Widget2(),
              )
            ]),
      ),
    ));
  }
}
