import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedLine11Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle66Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedUploadfotoWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle62Widget17.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedLine5Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle61Widget22.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle63Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle89Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle91Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle64Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle90Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedKategoriWidget7.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedBahasaWidget2.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle92Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedManageuserWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedpilihanmenuadminwidget1/generated/GeneratedRectangle65Widget.dart';

/* Frame Pilihan menu admin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPilihanmenuadminWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine5Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 80.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 47.0,
                child: GeneratedKategoriWidget7(),
              ),
              Positioned(
                left: 336.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 336.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 656.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine9Widget(),
              ),
              Positioned(
                left: 656.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine10Widget(),
              ),
              Positioned(
                left: 976.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 300.8321533203125,
                height: 1.0,
                child: GeneratedLine11Widget(),
              ),
              Positioned(
                left: 976.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 300.8321838378906,
                height: 1.0,
                child: GeneratedLine12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 160.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 611.0,
                height: 324.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 656.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 610.0,
                height: 324.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle61Widget22(),
              ),
              Positioned(
                left: 336.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle62Widget17(),
              ),
              Positioned(
                left: 180.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle65Widget(),
              ),
              Positioned(
                left: 816.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle66Widget(),
              ),
              Positioned(
                left: 656.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle63Widget7(),
              ),
              Positioned(
                left: 976.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 20.0,
                child: GeneratedRectangle64Widget10(),
              ),
              Positioned(
                left: 980.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 171.0,
                child: GeneratedRectangle89Widget(),
              ),
              Positioned(
                left: 990.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 30.0,
                child: GeneratedRectangle90Widget(),
              ),
              Positioned(
                left: 990.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 30.0,
                child: GeneratedRectangle91Widget7(),
              ),
              Positioned(
                left: 990.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 30.0,
                child: GeneratedRectangle92Widget(),
              ),
              Positioned(
                left: 1032.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 20.0,
                child: GeneratedManageuserWidget3(),
              ),
              Positioned(
                left: 1037.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 20.0,
                child: GeneratedUploadfotoWidget2(),
              ),
              Positioned(
                left: 1053.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 23.0,
                child: GeneratedBahasaWidget2(),
              )
            ]),
      ),
    ));
  }
}
