import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedAdaaktivitasmasukkeakunandazakieass_dariperangkatbarupa1.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedLine82Widget1.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedNotifikasiWidget3.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedImage31Widget1.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedLine83Widget1.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedLine81Widget1.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedAdarekomendasimakananbautandaSegeralihatsekarangWidget1.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedImage30Widget1.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedImage12Widget25.dart';
import 'package:flutterapp/makanterusapp/generatednotifikasiwidget2/generated/GeneratedRectangle157Widget1.dart';

/* Frame notifikasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotifikasiWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedRectangle157Widget1(),
              ),
              Positioned(
                left: 162.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 31.0,
                child: GeneratedNotifikasiWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage12Widget25(),
              ),
              Positioned(
                left: 70.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage30Widget1(),
              ),
              Positioned(
                left: 70.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedImage31Widget1(),
              ),
              Positioned(
                left: 115.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 41.0,
                child:
                    GeneratedAdaaktivitasmasukkeakunandazakieass_dariperangkatbarupa1(),
              ),
              Positioned(
                left: 32.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine81Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine82Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 1.0,
                child: GeneratedLine83Widget1(),
              ),
              Positioned(
                left: 115.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 28.0,
                child:
                    GeneratedAdarekomendasimakananbautandaSegeralihatsekarangWidget1(),
              )
            ]),
      ),
    ));
  }
}
