import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedLine52Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedLine38Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedLine37Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedLine51Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle55Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle54Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle51Widget26.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedLine48Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle57Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle40Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle38Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedLine47Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle39Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle58Widget16.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedTambahkanprodukdiskonWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedRectangle56Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget4/generated/GeneratedEllipse2Widget22.dart';

/* Frame Manage diskon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagediskonWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget8(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget8(),
              ),
              Positioned(
                left: 468.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 60.0,
                child: GeneratedRectangle40Widget8(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine37Widget11(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine38Widget11(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle51Widget26(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine47Widget7(),
              ),
              Positioned(
                left: 1250.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine48Widget6(),
              ),
              Positioned(
                left: 525.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 62.0,
                child: GeneratedTambahkanprodukdiskonWidget1(),
              ),
              Positioned(
                left: 150.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 980.0,
                height: 430.0,
                child: GeneratedRectangle58Widget16(),
              ),
              Positioned(
                left: 590.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse2Widget22(),
              ),
              Positioned(
                left: 603.33837890625,
                top: 415.0,
                right: null,
                bottom: null,
                width: 100.77328491210938,
                height: 0.49254661798477173,
                child: GeneratedLine51Widget2(),
              ),
              Positioned(
                left: 676.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 98.99494934082031,
                height: 1.0,
                child: GeneratedLine52Widget2(),
              ),
              Positioned(
                left: 580.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 50.0,
                child: GeneratedRectangle55Widget8(),
              ),
              Positioned(
                left: 440.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 35.0,
                child: GeneratedRectangle56Widget8(),
              ),
              Positioned(
                left: 520.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 30.0,
                child: GeneratedRectangle57Widget7(),
              ),
              Positioned(
                left: 300.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 50.0,
                child: GeneratedRectangle54Widget8(),
              )
            ]),
      ),
    ));
  }
}
