import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedRectangle64Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedVegetarianWidget6.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedChineseFoodWidget5.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedRectangle62Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedGroup47Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedJunkFoodWidget8.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedRectangle61Widget13.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedSnackWidget6.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedRectangle63Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget3/generated/GeneratedGroup48Widget8.dart';

/* Frame kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKategoriWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget8(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle61Widget13(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle62Widget5(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle63Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget8(),
              ),
              Positioned(
                left: 265.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 22.0,
                child: GeneratedJunkFoodWidget8(),
              ),
              Positioned(
                left: 45.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 22.0,
                child: GeneratedChineseFoodWidget5(),
              ),
              Positioned(
                left: 75.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 25.0,
                child: GeneratedSnackWidget6(),
              ),
              Positioned(
                left: 263.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 25.0,
                child: GeneratedVegetarianWidget6(),
              )
            ]),
      ),
    ));
  }
}
