import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup107Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup106Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup6Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup104Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedImage1Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedBackgroundWidget26.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup116Widget.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup103Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup46Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedRectangle41Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedMakanTerusWidget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup109Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup102Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedBackgroundWidget27.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup105Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget/generated/GeneratedGroup108Widget2.dart';

/* Frame Bahasa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBahasaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 25.0,
                child: GeneratedMakanTerusWidget3(),
              ),
              Positioned(
                left: 326.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 20.0,
                child: GeneratedGroup6Widget3(),
              ),
              Positioned(
                left: 370.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedImage1Widget3(),
              ),
              Positioned(
                left: 46.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 55.0,
                child: GeneratedRectangle41Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup105Widget3(),
              ),
              Positioned(
                left: 216.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup102Widget3(),
              ),
              Positioned(
                left: 216.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup103Widget3(),
              ),
              Positioned(
                left: 48.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup104Widget3(),
              ),
              Positioned(
                left: 47.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 168.0,
                child: GeneratedGroup107Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget26(),
              ),
              Positioned(
                left: 401.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget27(),
              ),
              Positioned(
                left: 39.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup109Widget2(),
              ),
              Positioned(
                left: 226.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup108Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup46Widget2(),
              ),
              Positioned(
                left: 240.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 130.0,
                child: GeneratedGroup116Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup106Widget2(),
              )
            ]),
      ),
    ));
  }
}
