import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedImage24Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedImage21Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedPromomerdekaWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedGroup48Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedImage20Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedImage23Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedImage22Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedGroup47Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedDiskonflashdealWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedRectangle61Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedDiskonLamianPalaceWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedTambahkandiskonWidget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedImage15Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagediskonwidget1/generated/GeneratedImage18Widget2.dart';

/* Frame Manage diskon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagediskonWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle61Widget6(),
              ),
              Positioned(
                left: 87.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 45.0,
                child: GeneratedTambahkandiskonWidget(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedImage20Widget(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedImage24Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedImage21Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget3(),
              ),
              Positioned(
                left: 360.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget6(),
              ),
              Positioned(
                left: 160.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage22Widget(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage23Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage18Widget2(),
              ),
              Positioned(
                left: 249.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 49.0,
                child: GeneratedDiskonLamianPalaceWidget(),
              ),
              Positioned(
                left: 39.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 24.0,
                child: GeneratedPromomerdekaWidget(),
              ),
              Positioned(
                left: 272.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 46.0,
                child: GeneratedDiskonflashdealWidget(),
              )
            ]),
      ),
    ));
  }
}
