import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedVegetarianWidget9.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedGroup47Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedGroup48Widget10.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedJunkFoodWidget12.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedSnackWidget9.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedRectangle64Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedRectangle63Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedRectangle62Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedRectangle61Widget19.dart';
import 'package:flutterapp/makanterusapp/generatedkategoriwidget5/generated/GeneratedChineseFoodWidget8.dart';

/* Frame kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKategoriWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget10(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle61Widget19(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle62Widget12(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle63Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget12(),
              ),
              Positioned(
                left: 265.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 22.0,
                child: GeneratedJunkFoodWidget12(),
              ),
              Positioned(
                left: 45.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 22.0,
                child: GeneratedChineseFoodWidget8(),
              ),
              Positioned(
                left: 75.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 25.0,
                child: GeneratedSnackWidget9(),
              ),
              Positioned(
                left: 263.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 25.0,
                child: GeneratedVegetarianWidget9(),
              )
            ]),
      ),
    ));
  }
}
