import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle51Widget24.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedLine51Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedEllipse2Widget20.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle38Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle56Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedTambahkankategoriWidget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle57Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedLine47Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedLine38Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle39Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle58Widget14.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedLine37Widget9.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle55Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle54Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedLine52Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedRectangle40Widget6.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget4/generated/GeneratedLine48Widget4.dart';

/* Frame Manage kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagekategoriWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget6(),
              ),
              Positioned(
                left: 468.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 60.0,
                child: GeneratedRectangle40Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine37Widget9(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine38Widget9(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle51Widget24(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine47Widget5(),
              ),
              Positioned(
                left: 1250.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine48Widget4(),
              ),
              Positioned(
                left: 468.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 44.0,
                child: GeneratedTambahkankategoriWidget4(),
              ),
              Positioned(
                left: 150.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 980.0,
                height: 430.0,
                child: GeneratedRectangle58Widget14(),
              ),
              Positioned(
                left: 590.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedEllipse2Widget20(),
              ),
              Positioned(
                left: 603.33837890625,
                top: 415.0,
                right: null,
                bottom: null,
                width: 100.77328491210938,
                height: 0.49254661798477173,
                child: GeneratedLine51Widget(),
              ),
              Positioned(
                left: 676.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 98.99494934082031,
                height: 1.0,
                child: GeneratedLine52Widget(),
              ),
              Positioned(
                left: 580.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 50.0,
                child: GeneratedRectangle55Widget6(),
              ),
              Positioned(
                left: 440.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 35.0,
                child: GeneratedRectangle56Widget6(),
              ),
              Positioned(
                left: 520.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 30.0,
                child: GeneratedRectangle57Widget5(),
              ),
              Positioned(
                left: 300.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 50.0,
                child: GeneratedRectangle54Widget6(),
              )
            ]),
      ),
    ));
  }
}
