import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedGroup32Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine42Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle44Widget7.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine46Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedGroup31Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine39Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle42Widget7.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine37Widget3.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine48Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle46Widget1.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle41Widget6.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle49Widget6.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine38Widget3.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle51Widget20.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedJunkFoodWidget14.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle45Widget8.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine43Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle45Widget7.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine44Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine47Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine45Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine41Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle50Widget6.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedLine40Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedRectangle43Widget7.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/makanterusapp/generateddeleteartikelwidget/generated/GeneratedGroup27Widget.dart';

/* Frame Delete artikel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeleteartikelWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 480.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRectangle40Widget(),
              ),
              Positioned(
                left: 552.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 44.0,
                child: GeneratedJunkFoodWidget14(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine37Widget3(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine38Widget3(),
              ),
              Positioned(
                left: 95.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle41Widget6(),
              ),
              Positioned(
                left: 95.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle43Widget7(),
              ),
              Positioned(
                left: 480.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup28Widget(),
              ),
              Positioned(
                left: 480.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup27Widget(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle42Widget7(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle44Widget7(),
              ),
              Positioned(
                left: 95.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine39Widget(),
              ),
              Positioned(
                left: 515.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine40Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine41Widget(),
              ),
              Positioned(
                left: 505.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine42Widget(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine43Widget(),
              ),
              Positioned(
                left: 1185.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine44Widget(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine45Widget(),
              ),
              Positioned(
                left: 1185.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine46Widget(),
              ),
              Positioned(
                left: 205.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle45Widget7(),
              ),
              Positioned(
                left: 875.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle49Widget6(),
              ),
              Positioned(
                left: 105.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 403.0,
                height: 10.0,
                child: GeneratedRectangle46Widget(),
              ),
              Positioned(
                left: 775.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle50Widget6(),
              ),
              Positioned(
                left: 205.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle45Widget8(),
              ),
              Positioned(
                left: 875.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle47Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle46Widget1(),
              ),
              Positioned(
                left: 775.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle51Widget20(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine47Widget(),
              ),
              Positioned(
                left: 1250.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine48Widget(),
              ),
              Positioned(
                left: 480.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: 1150.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup30Widget(),
              ),
              Positioned(
                left: 1150.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup31Widget(),
              ),
              Positioned(
                left: 480.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedGroup29Widget(),
              ),
              Positioned(
                left: 524.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 30.0,
                child: GeneratedGroup32Widget(),
              )
            ]),
      ),
    ));
  }
}
