import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup46Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedBackgroundWidget35.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedMakanTerusWidget5.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedBackgroundWidget34.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup105Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup103Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup106Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedRectangle41Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup116Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup6Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup102Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup108Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup109Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup107Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedbahasawidget1/generated/GeneratedGroup104Widget5.dart';

/* Frame Bahasa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBahasaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 414.0,
        height: 736.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 25.0,
                child: GeneratedMakanTerusWidget5(),
              ),
              Positioned(
                left: 356.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 20.0,
                child: GeneratedGroup6Widget5(),
              ),
              Positioned(
                left: 46.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 55.0,
                child: GeneratedRectangle41Widget4(),
              ),
              Positioned(
                left: 48.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup105Widget5(),
              ),
              Positioned(
                left: 216.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup102Widget5(),
              ),
              Positioned(
                left: 216.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup103Widget5(),
              ),
              Positioned(
                left: 48.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 50.0,
                child: GeneratedGroup104Widget5(),
              ),
              Positioned(
                left: 47.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 168.0,
                child: GeneratedGroup107Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget34(),
              ),
              Positioned(
                left: 401.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 140.0,
                child: GeneratedBackgroundWidget35(),
              ),
              Positioned(
                left: 39.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup109Widget4(),
              ),
              Positioned(
                left: 226.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 135.0,
                child: GeneratedGroup108Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup46Widget4(),
              ),
              Positioned(
                left: 249.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 130.0,
                child: GeneratedGroup116Widget1(),
              ),
              Positioned(
                left: 65.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedGroup106Widget3(),
              )
            ]),
      ),
    ));
  }
}
