import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine44Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine38Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle4Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine47Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle43Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine13Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle49Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine42Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle38Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle50Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle44Widget12.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine40Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle48Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle45Widget15.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle47Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle40Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle45Widget14.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle41Widget11.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle46Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine37Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine46Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle46Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine14Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine45Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedJunkFoodWidget16.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine41Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine39Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedLine43Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle39Widget5.dart';
import 'package:flutterapp/makanterusapp/generatedisikategoriwidget3/generated/GeneratedRectangle42Widget12.dart';

/* Frame Isi kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIsikategoriWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1280.0,
        height: 720.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1280.0,
                height: 150.0,
                child: GeneratedRectangle38Widget5(),
              ),
              Positioned(
                left: 1170.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine14Widget7(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle4Widget11(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedRectangle39Widget5(),
              ),
              Positioned(
                left: 480.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 60.0,
                child: GeneratedRectangle40Widget5(),
              ),
              Positioned(
                left: 552.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 44.0,
                child: GeneratedJunkFoodWidget16(),
              ),
              Positioned(
                left: 1170.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine13Widget7(),
              ),
              Positioned(
                left: 1170.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 113.1370849609375,
                height: 1.0,
                child: GeneratedLine47Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine37Widget8(),
              ),
              Positioned(
                left: 80.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 84.85281372070312,
                height: 1.0,
                child: GeneratedLine38Widget8(),
              ),
              Positioned(
                left: 95.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle41Widget11(),
              ),
              Positioned(
                left: 95.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle43Widget12(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle42Widget12(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 420.0,
                height: 200.0,
                child: GeneratedRectangle44Widget12(),
              ),
              Positioned(
                left: 95.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine39Widget2(),
              ),
              Positioned(
                left: 515.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine40Widget2(),
              ),
              Positioned(
                left: 85.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine41Widget5(),
              ),
              Positioned(
                left: 505.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine42Widget5(),
              ),
              Positioned(
                left: 765.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine43Widget5(),
              ),
              Positioned(
                left: 1185.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine44Widget5(),
              ),
              Positioned(
                left: 765.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine45Widget5(),
              ),
              Positioned(
                left: 1185.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 465.1881408691406,
                height: 1.0,
                child: GeneratedLine46Widget5(),
              ),
              Positioned(
                left: 205.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle45Widget14(),
              ),
              Positioned(
                left: 875.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle49Widget11(),
              ),
              Positioned(
                left: 105.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 403.0,
                height: 10.0,
                child: GeneratedRectangle46Widget7(),
              ),
              Positioned(
                left: 775.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle50Widget11(),
              ),
              Positioned(
                left: 205.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle45Widget15(),
              ),
              Positioned(
                left: 875.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 10.0,
                child: GeneratedRectangle47Widget5(),
              ),
              Positioned(
                left: 105.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle46Widget8(),
              ),
              Positioned(
                left: 775.0,
                top: 670.0,
                right: null,
                bottom: null,
                width: 400.0,
                height: 10.0,
                child: GeneratedRectangle48Widget5(),
              )
            ]),
      ),
    ));
  }
}
