import 'package:flutter/material.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedRectangle67Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedImage15Widget7.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedLine38Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedGroup119Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedRectangle63Widget2.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedGroup47Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedGroup86Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedTambahkankategoriWidget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedRectangle68Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedGroup94Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedJunkFoodWidget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedImage18Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedLine37Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedRectangle128Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedLine36Widget.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedGroup84Widget1.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedGroup48Widget4.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedRectangle61Widget8.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedRectangle64Widget3.dart';
import 'package:flutterapp/makanterusapp/generatedmanagekategoriwidget2/generated/GeneratedLine35Widget.dart';

/* Frame Manage kategori
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedManagekategoriWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 95.0,
                child: GeneratedGroup48Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle61Widget8(),
              ),
              Positioned(
                left: 80.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 45.0,
                child: GeneratedTambahkankategoriWidget1(),
              ),
              Positioned(
                left: 224.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle128Widget(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle63Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 165.0,
                child: GeneratedRectangle64Widget3(),
              ),
              Positioned(
                left: 254.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 44.0,
                child: GeneratedRectangle67Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 567.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 44.0,
                child: GeneratedRectangle68Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 99.0,
                child: GeneratedGroup47Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.90716552734375,
                height: 1.0,
                child: GeneratedLine35Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine36Widget(),
              ),
              Positioned(
                left: 224.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine37Widget(),
              ),
              Positioned(
                left: 394.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 236.9071502685547,
                height: 1.0,
                child: GeneratedLine38Widget(),
              ),
              Positioned(
                left: 360.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedImage15Widget7(),
              ),
              Positioned(
                left: 160.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup84Widget1(),
              ),
              Positioned(
                left: 360.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedGroup86Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage18Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 341.0,
                child: GeneratedGroup94Widget(),
              ),
              Positioned(
                left: 265.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 22.0,
                child: GeneratedJunkFoodWidget4(),
              ),
              Positioned(
                left: 102.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 145.0,
                child: GeneratedGroup119Widget(),
              )
            ]),
      ),
    ));
  }
}
